<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./checkpoint.glb -T -t --shadows -r /assets/basic-vehicle-controller/
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group, Mesh } from 'three'
  import { createRawEventDispatcher, T, useFrame } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { Collider, CollisionGroups } from '@threlte/rapier'

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      CheckpointTopSign: THREE.Mesh
      CheckpointTopTopPlate: THREE.Mesh
      CheckpointTopTopPlate001: THREE.Mesh
      CheckpointBase: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      HalfBox: THREE.MeshStandardMaterial
    }
  }

  const dispatch = createRawEventDispatcher<{
    checkpointreached: undefined
  }>()

  const gltf = useGltf<GLTFResult>('/assets/basic-vehicle-controller/checkpoint-transformed.glb', {
    useDraco: true
  })

  let signMesh: Mesh

  let reached = false

  $: signMaterial = $gltf?.materials.Material.clone()

  useFrame(() => {
    if (!signMesh) return
    signMesh.rotation.y -= 0.007
  })
</script>

{#if $gltf}
  <T is={ref}>
    <T.Group position.y={-2.5}>
      <Collider
        shape="cuboid"
        args={[5, 2.5, 5]}
        type="dynamic"
      />
    </T.Group>
    <T.Group position={[0, 5, 0]}>
      {#if signMaterial}
        <T.Mesh
          bind:ref={signMesh}
          castShadow
          receiveShadow
          geometry={$gltf.nodes.CheckpointTopSign.geometry}
          material={signMaterial}
          position={[0, -0.38, 0]}
          material.color="#606060"
          material.roughness={0.3}
          material.metalness={0.3}
          material.emissive={reached ? 'green' : 'red'}
        >
          <Collider
            shape="cylinder"
            args={[0.35, 2.5]}
            type="dynamic"
          />
        </T.Mesh>
      {/if}
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.CheckpointTopTopPlate.geometry}
        material={$gltf.materials.HalfBox}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.CheckpointTopTopPlate001.geometry}
        material={$gltf.materials.HalfBox}
        position={[0, -0.62, 0]}
        scale={[0.96, 1, 0.96]}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.CheckpointBase.geometry}
      material={$gltf.materials.HalfBox}
    />

    <slot {ref} />

    <T.Group position.y={2.5}>
      <CollisionGroups groups={[3]}>
        <Collider
          type="dynamic"
          shape="cuboid"
          args={[5, 2.5, 5]}
          on:sensorenter={() => {
            reached = true
            dispatch('checkpointreached')
          }}
          sensor
        />
      </CollisionGroups>
    </T.Group>
  </T>
{/if}
