<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./ramp.glb -T -t --shadows -r /assets/basic-vehicle-controller/
-->
<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { Collider } from '@threlte/rapier'
  import type * as THREE from 'three'
  import { Group } from 'three'
  import Selection from './Selection.svelte'

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      HalfBox: THREE.Mesh
    }
    materials: {
      HalfBox: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/assets/basic-vehicle-controller/halfbox-transformed.glb', {
    useDraco: true
  })

  export let selected: boolean
</script>

{#if $gltf}
  <T is={ref}>
    <T.Group position.y={-2.5}>
      <Collider
        shape="cuboid"
        args={[5, 2.5, 5]}
        type="dynamic"
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.HalfBox.geometry}
    >
      <T is={$gltf.materials.HalfBox} />
      {#if selected}
        <Selection />
      {/if}
    </T.Mesh>

    <slot {ref} />
  </T>
{/if}
