<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./ramp.glb -T -t --shadows -r /assets/basic-vehicle-controller/
-->
<script lang="ts">
  import type { ISheetObject } from '@theatre/core'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { AutoColliders } from '@threlte/rapier'
  import type * as THREE from 'three'
  import { Group } from 'three'
  import Selection from './Selection.svelte'
  import { useSheetObjectToUpdateAutoColliders } from './useSheetObjectToUpdateAutoColliders'

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      RampInverse: THREE.Mesh
    }
    materials: {
      Ramps: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(
    '/assets/basic-vehicle-controller/ramp_inverse-transformed.glb',
    {
      useDraco: true
    }
  )

  export let sheetObject: ISheetObject | undefined = undefined
  const { refresh } = useSheetObjectToUpdateAutoColliders(sheetObject)

  export let selected: boolean = false
</script>

{#if $gltf}
  <T is={ref}>
    <AutoColliders
      shape="trimesh"
      bind:refresh={$refresh}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.RampInverse.geometry}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T is={$gltf.materials.Ramps} />
        {#if selected}
          <Selection />
        {/if}
      </T.Mesh>
    </AutoColliders>

    <slot {ref} />
  </T>
{/if}
