<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./ramp.glb -T -t --shadows -r /assets/basic-vehicle-controller/
-->
<script lang="ts">
  import type { ISheetObject } from '@theatre/core'
  import { T, type Events, type Props, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { AutoColliders } from '@threlte/rapier'
  import { onDestroy, onMount, tick } from 'svelte'
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { useSheetObjectToUpdateAutoColliders } from './useSheetObjectToUpdateAutoColliders'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/assets/basic-vehicle-controller/ramp-transformed.glb', {
    useDraco: true
  })

  export let sheetObject: ISheetObject
  const { refresh } = useSheetObjectToUpdateAutoColliders(sheetObject)
</script>

{#if $gltf}
  <T
    is={ref}
    {...$$restProps}
    name="Ramp"
  >
    <AutoColliders
      shape="trimesh"
      bind:refresh={$refresh}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.Cylinder.geometry}
        material={$gltf.materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </AutoColliders>

    <slot {ref} />
  </T>
{/if}
