<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./low_poly_race_track.glb -T -t
Author: Quarks Studios (https://sketchfab.com/QuarksStudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-race-track-b40628339fde4b2fbe41711edc7c7a93
Title: Low poly race track
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube_Material001_0: THREE.Mesh
      Cube_Material_0: THREE.Mesh
      Cube001_Material001_0: THREE.Mesh
      Cube001_Material003_0: THREE.Mesh
      Cube001_Material002_0: THREE.Mesh
      Cube002_Material001_0: THREE.Mesh
      Cube002_Material_0: THREE.Mesh
      Cube003_Material001_0: THREE.Mesh
      Cube003_Material_0: THREE.Mesh
      Cube011_Material001_0: THREE.Mesh
      Cube011_Material003_0: THREE.Mesh
      Cube011_Material002_0: THREE.Mesh
      Cube012_Material001_0: THREE.Mesh
      Cube012_Material_0: THREE.Mesh
      Cube013_Material001_0: THREE.Mesh
      Cube013_Material003_0: THREE.Mesh
      Cube013_Material002_0: THREE.Mesh
      Cube004_Material001_0: THREE.Mesh
      Cube004_Material_0: THREE.Mesh
      Cube005_Material001_0: THREE.Mesh
      Cube005_Material_0: THREE.Mesh
      Cube006_Material001_0: THREE.Mesh
      Cube006_Material003_0: THREE.Mesh
      Cube006_Material002_0: THREE.Mesh
      Cube007_Material001_0: THREE.Mesh
      Cube007_Material003_0: THREE.Mesh
      Cube007_Material002_0: THREE.Mesh
      Cube008_Material001_0: THREE.Mesh
      Cube008_Material_0: THREE.Mesh
      Cube009_Material_0: THREE.Mesh
      Cube009_Material001_0: THREE.Mesh
      Cube010_Material001_0: THREE.Mesh
      Cube010_Material003_0: THREE.Mesh
      Cube010_Material002_0: THREE.Mesh
      Cube014_Material001_0: THREE.Mesh
      Cube014_Material_0: THREE.Mesh
      Cube015_Material001_0: THREE.Mesh
      Cube015_Material003_0: THREE.Mesh
      Cube015_Material002_0: THREE.Mesh
      Cube016_Material001_0: THREE.Mesh
      Cube016_Material_0: THREE.Mesh
      Cube017_Material001_0: THREE.Mesh
      Cube017_Material_0: THREE.Mesh
      Cube018_Material001_0: THREE.Mesh
      Cube018_Material_0: THREE.Mesh
      Cube019_Material001_0: THREE.Mesh
      Cube019_Material_0: THREE.Mesh
      Cube019_Material005_0: THREE.Mesh
      Cube020_Material001_0: THREE.Mesh
      Cube020_Material_0: THREE.Mesh
      Cube021_Material001_0: THREE.Mesh
      Cube021_Material003_0: THREE.Mesh
      Cube021_Material002_0: THREE.Mesh
      Cube022_Material001_0: THREE.Mesh
      Cube022_Material_0: THREE.Mesh
      Cube023_Material001_0: THREE.Mesh
      Cube023_Material003_0: THREE.Mesh
      Cube023_Material002_0: THREE.Mesh
      Cube024_Material001_0: THREE.Mesh
      Cube024_Material_0: THREE.Mesh
      Cube025_Material001_0: THREE.Mesh
      Cube025_Material003_0: THREE.Mesh
      Cube025_Material002_0: THREE.Mesh
      Cube026_Material001_0: THREE.Mesh
      Cube026_Material_0: THREE.Mesh
      Cube027_Material001_0: THREE.Mesh
      Cube027_Material_0: THREE.Mesh
      Cube028_Material001_0: THREE.Mesh
      Cube028_Material_0: THREE.Mesh
      Cube029_Material001_0: THREE.Mesh
      Cube029_Material_0: THREE.Mesh
      Cube030_Material001_0: THREE.Mesh
      Cube030_Material_0: THREE.Mesh
      Cube031_Material001_0: THREE.Mesh
      Cube031_Material_0: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
      Material: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(
    '/assets/basic-vehicle-controller/low_poly_race_track-transformed.glb',
    { useDraco: true }
  )
</script>

{#if $gltf}
  <T
    is={ref}
    {...$$restProps}
  >
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Group
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <T.Group
          position={[1566.06, 196.45, -3529.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[-13817.65, 196.45, 7453.29]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube001_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube001_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube001_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[17227.74, 196.45, 32542.19]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube002_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube002_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[15013.7, 196.45, 14883.67]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube003_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube003_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[6962.13, 196.45, 1568.77]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube011_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube011_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube011_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[-2733.94, 196.45, -3529.2]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube012_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube012_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[-3626.91, 196.45, -3330.4]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube013_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube013_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube013_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[-8722.9, 196.45, 2065.28]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube004_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube004_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[-14703.88, 196.45, 7651.56]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube005_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube005_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[-15595.63, 196.45, 7849.48]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube006_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube006_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube006_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[-20492.14, 196.45, 9786.93]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube007_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube007_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube007_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[-15103.88, 196.45, 14884.29]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube008_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube008_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[23671.54, 196.45, 14884.29]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube009_Material_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube009_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
        </T.Group>
        <T.Group
          position={[29048.49, 196.45, 19979]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube010_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube010_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube010_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[29248.16, 196.45, 20862.81]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube014_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube014_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[24152.19, 196.45, 32343.12]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube015_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube015_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube015_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[21547.49, 196.45, 32541.87]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube016_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube016_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[5500.9, 196.45, 32584.36]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube017_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube017_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[7162.54, 196.45, 2458.46]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube018_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube018_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[7162.54, 196.45, 6785.28]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube019_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube019_Material_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube019_Material005_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[7162.54, 196.45, 11109.57]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube020_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube020_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[2066.72, 196.45, 20802.39]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube021_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube021_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube021_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[1566.06, 196.45, 21003.53]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube022_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube022_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[675.86, 196.45, 21203.78]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube023_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube023_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube023_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[-4420.16, 196.45, 26595.67]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube024_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube024_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[-4220.75, 196.45, 27486.93]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube025_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube025_Material003_0.geometry}
            material={$gltf.materials.Material}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube025_Material002_0.geometry}
            material={$gltf.materials['Material.002']}
          />
        </T.Group>
        <T.Group
          position={[1173.29, 196.45, 32584.77]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube026_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube026_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[29248.16, 196.45, 23930]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube027_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube027_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[24568.31, 196.45, 32541.87]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube028_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube028_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[29248.16, 196.45, 26962.81]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube029_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube029_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[7162.54, 196.45, 15404.27]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube030_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube030_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
        <T.Group
          position={[-10761.16, 196.45, 14884.29]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={100}
        >
          <T.Mesh
            geometry={$gltf.nodes.Cube031_Material001_0.geometry}
            material={$gltf.materials['Material.001']}
          />
          <T.Mesh
            geometry={$gltf.nodes.Cube031_Material_0.geometry}
            material={$gltf.materials.Material}
          />
        </T.Group>
      </T.Group>
    </T.Group>

    <slot {ref} />
  </T>
{/if}
