<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./muscle-car-wheel.glb -T -t
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube002: THREE.Mesh
      Cube002_1: THREE.Mesh
      Cube002_2: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.007']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(
    '/assets/basic-vehicle-controller/muscle-car-wheel-transformed.glb',
    { useDraco: true }
  )
</script>

{#if $gltf}
  <T
    is={ref}
    {...$$restProps}
  >
    <T.Group scale={0.37}>
      <T.Mesh
        geometry={$gltf.nodes.Cube002.geometry}
        material={$gltf.materials['Material.001']}
      />
      <T.Mesh
        geometry={$gltf.nodes.Cube002_1.geometry}
        material={$gltf.materials['Material.002']}
      />
      <T.Mesh
        geometry={$gltf.nodes.Cube002_2.geometry}
        material={$gltf.materials['Material.007']}
      />
    </T.Group>

    <slot {ref} />
  </T>
{/if}
