<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./muscle-car.glb -T -t
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group> & {
    braking?: boolean
  }
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  export let isBraking = false

  type GLTFResult = {
    nodes: {
      Cube_1: THREE.Mesh
      Cube_2: THREE.Mesh
      Cube_3: THREE.Mesh
      Cube_4: THREE.Mesh
      Cube_5: THREE.Mesh
      Cube_6: THREE.Mesh
      Cube_7: THREE.Mesh
      Cube_8: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.003']: THREE.MeshStandardMaterial
      ['Material.004']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
      ['Material.006']: THREE.MeshStandardMaterial
      ['Material.008']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/assets/basic-vehicle-controller/muscle-car-transformed.glb', {
    useDraco: true
  })
</script>

{#if $gltf}
  <T
    is={ref}
    {...$$restProps}
  >
    <T.Group scale={[0.37, 0.31, 2.2]}>
      <T.Mesh
        castShadow
        geometry={$gltf.nodes.Cube_1.geometry}
        material={$gltf.materials.Material}
        material.color="#FE3D00"
      />
      <T.Mesh
        castShadow
        geometry={$gltf.nodes.Cube_2.geometry}
        material={$gltf.materials['Material.001']}
      />
      <T.Mesh
        castShadow
        geometry={$gltf.nodes.Cube_3.geometry}
        material={$gltf.materials['Material.003']}
      />
      <T.Mesh
        name="Lights"
        castShadow
        geometry={$gltf.nodes.Cube_4.geometry}
        material={$gltf.materials['Material.004']}
        material.emissive={isBraking ? 'red' : 'black'}
        material.envMapIntensity={0}
        material.emissiveIntensity={1}
      />
      <T.Mesh
        castShadow
        geometry={$gltf.nodes.Cube_5.geometry}
        material={$gltf.materials['Material.005']}
      />
      <T.Mesh
        castShadow
        geometry={$gltf.nodes.Cube_6.geometry}
        material={$gltf.materials['Material.006']}
      />
      <T.Mesh
        castShadow
        geometry={$gltf.nodes.Cube_7.geometry}
        material={$gltf.materials['Material.006']}
      />
      <T.Mesh
        castShadow
        geometry={$gltf.nodes.Cube_8.geometry}
        material={$gltf.materials['Material.008']}
      />
    </T.Group>

    <slot {ref} />
  </T>
{/if}
