<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./wallride.glb -T -t --shadows -r /assets/basic-vehicle-controller/
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { DoubleSide, Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { AutoColliders } from '@threlte/rapier'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cylinder002: THREE.Mesh
      Cylinder: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/assets/basic-vehicle-controller/wallride-transformed.glb', {
    useDraco: true
  })
</script>

{#if $gltf}
  <T
    is={ref}
    {...$$restProps}
  >
    <AutoColliders
      shape="trimesh"
      friction={0}
      frictionCombineRule={0}
      restitution={0}
      restitutionCombineRule={0}
    >
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.Cylinder002.geometry}
        material={$gltf.nodes.Cylinder002.material}
        position={[0, 1, 0]}
        material.side={DoubleSide}
        material.flatShading={false}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.Cylinder.geometry}
        material={$gltf.nodes.Cylinder.material}
        position={[0, 1, 1]}
        rotation={[Math.PI / 2, 0, 0]}
        material.side={DoubleSide}
        material.flatShading={false}
      />
    </AutoColliders>

    <slot {ref} />
  </T>
{/if}
