<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./amgone.glb -T -t --shadows -r /assets/basic-vehicle-controller/
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Object_10: THREE.Mesh
      Object_11: THREE.Mesh
      Object_12: THREE.Mesh
      Object_14: THREE.Mesh
      Object_15: THREE.Mesh
      Object_16: THREE.Mesh
      Object_17: THREE.Mesh
      Object_18: THREE.Mesh
      Object_19: THREE.Mesh
      Object_2: THREE.Mesh
      Object_20: THREE.Mesh
      Object_21: THREE.Mesh
      Object_22: THREE.Mesh
      Object_23: THREE.Mesh
      Object_24: THREE.Mesh
      Object_25: THREE.Mesh
      Object_26: THREE.Mesh
      Object_28: THREE.Mesh
      Object_29: THREE.Mesh
      Object_3: THREE.Mesh
      Object_31: THREE.Mesh
      Object_33: THREE.Mesh
      Object_34: THREE.Mesh
      Object_35: THREE.Mesh
      Object_36: THREE.Mesh
      Object_4: THREE.Mesh
      Object_5: THREE.Mesh
      Object_6: THREE.Mesh
      Object_7: THREE.Mesh
      Object_8: THREE.Mesh
      Object_9: THREE.Mesh
    }
    materials: {
      STERRING_DECALS: THREE.MeshStandardMaterial
      SEAT_BELT: THREE.MeshStandardMaterial
      CARBON_FIBER: THREE.MeshPhysicalMaterial
      CHROME_RED: THREE.MeshStandardMaterial
      CHROME_ROUGH: THREE.MeshStandardMaterial
      BAKE_DISK: THREE.MeshStandardMaterial
      METAL_BLACK: THREE.MeshPhysicalMaterial
      PLASTIC_BLACK_SHINNY: THREE.MeshStandardMaterial
      SCREEN: THREE.MeshPhysicalMaterial
      CARPAINT_2: THREE.MeshPhysicalMaterial
      PLASTIC_RUBBER: THREE.MeshStandardMaterial
      PLASTIC_SHINNY: THREE.MeshStandardMaterial
      NUMBERPLATE: THREE.MeshStandardMaterial
      HEADLIGHT_GLASS: THREE.MeshStandardMaterial
      LEATHER_BLACK: THREE.MeshStandardMaterial
      MERCEDES_LOGO: THREE.MeshStandardMaterial
      GAPFILL: THREE.MeshStandardMaterial
      TAILLIGHT_GLASS: THREE.MeshStandardMaterial
      CHROME: THREE.MeshStandardMaterial
      ALLOY: THREE.MeshPhysicalMaterial
      GRILL: THREE.MeshStandardMaterial
      PIANO_BLACK: THREE.MeshStandardMaterial
      RADIATOR: THREE.MeshStandardMaterial
      DECALS: THREE.MeshStandardMaterial
      CHROME_BLACK: THREE.MeshStandardMaterial
      CARPAINT: THREE.MeshPhysicalMaterial
      GRILL_2: THREE.MeshStandardMaterial
      MIRROR: THREE.MeshStandardMaterial
      PLASTIC_BLACK: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(
    '/../../Users/grischaerbe/Documents/Projects/2022/threlte/apps/docs-next/public/assets/basic-vehicle-controller/amgone-transformed.glb',
    { useDraco: true }
  )
</script>

{#if $gltf}
  <T is={ref} {...$$restProps}>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_10.geometry}
      material={$gltf.materials.STERRING_DECALS}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_11.geometry}
      material={$gltf.materials.SEAT_BELT}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_12.geometry}
      material={$gltf.materials.CARBON_FIBER}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_14.geometry}
      material={$gltf.materials.CHROME_RED}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_15.geometry}
      material={$gltf.materials.CHROME_ROUGH}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_16.geometry}
      material={$gltf.materials.BAKE_DISK}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_17.geometry}
      material={$gltf.materials.METAL_BLACK}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_18.geometry}
      material={$gltf.materials.PLASTIC_BLACK_SHINNY}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_19.geometry}
      material={$gltf.materials.SCREEN}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_2.geometry}
      material={$gltf.materials.CARPAINT_2}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_20.geometry}
      material={$gltf.materials.PLASTIC_RUBBER}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_21.geometry}
      material={$gltf.materials.PLASTIC_SHINNY}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_22.geometry}
      material={$gltf.materials.NUMBERPLATE}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_23.geometry}
      material={$gltf.materials.HEADLIGHT_GLASS}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_24.geometry}
      material={$gltf.materials.LEATHER_BLACK}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_25.geometry}
      material={$gltf.materials.MERCEDES_LOGO}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_26.geometry}
      material={$gltf.materials.GAPFILL}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_28.geometry}
      material={$gltf.materials.HEADLIGHT_GLASS}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_29.geometry}
      material={$gltf.materials.TAILLIGHT_GLASS}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_3.geometry}
      material={$gltf.materials.CHROME}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_31.geometry}
      material={$gltf.materials.ALLOY}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_33.geometry}
      material={$gltf.materials.GRILL}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_34.geometry}
      material={$gltf.materials.PIANO_BLACK}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_35.geometry}
      material={$gltf.materials.RADIATOR}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_36.geometry}
      material={$gltf.materials.DECALS}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_4.geometry}
      material={$gltf.materials.CHROME_BLACK}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_5.geometry}
      material={$gltf.materials.CARPAINT}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_6.geometry}
      material={$gltf.materials.GRILL_2}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_7.geometry}
      material={$gltf.materials.MIRROR}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_8.geometry}
      material={$gltf.materials.PLASTIC_BLACK}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.Object_9.geometry}
      material={$gltf.materials.HEADLIGHT_GLASS}
      position={[0, -0.1, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
    />

    <slot {ref} />
  </T>
{/if}
