<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.0 ./checkpoint.glb -T -t --shadows -r /assets/basic-vehicle-controller/
-->
<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      CheckpointTopSign: THREE.Mesh
      CheckpointTopTopPlate: THREE.Mesh
      CheckpointTopTopPlate001: THREE.Mesh
      CheckpointBase: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      HalfBox: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(
    '/../../Users/grischaerbe/Documents/Projects/2022/threlte/apps/docs-next/public/assets/basic-vehicle-controller/checkpoint-transformed.glb',
    { useDraco: true }
  )
</script>

{#if $gltf}
  <T is={ref} {...$$restProps}>
    <T.Group position={[0, 5, 0]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.CheckpointTopSign.geometry}
        material={$gltf.materials.Material}
        position={[0, -0.38, 0]}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.CheckpointTopTopPlate.geometry}
        material={$gltf.materials.HalfBox}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={$gltf.nodes.CheckpointTopTopPlate001.geometry}
        material={$gltf.materials.HalfBox}
        position={[0, -0.62, 0]}
        scale={[0.96, 1, 0.96]}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={$gltf.nodes.CheckpointBase.geometry}
      material={$gltf.materials.HalfBox}
    />

    <slot {ref} />
  </T>
{/if}
